### ISSUE TITLE
Plugin break when Cloudflare enabled 

### ISSUE THREAD

**Issue by sam24fs** [2Checkout/woocommerce#18]
The inline plugins give an error when Cloudflare is enabled on the Woocomerce website.

**Payment error: The shopper IP is not valid**

Screenshot https://snipboard.io/Lwqdst.jpg

I would appreciate it if you could provide a solution.

**Comment by craigchristenson** [comment]
Thanks for reporting this issue. This was fixed in the latest release 1.2.1.
