### ISSUE TITLE
Order status is marked as 'UNFINISHED'

### ISSUE THREAD

**Issue by sam24fs** [2Checkout/woocommerce#19]
We see a different issue after the update. When a customer makes a payment the card is charged but the Order status is marked as 'UNFINISHED'

(Screenshot attached) 

Could you please look into this matter ASAP? 
![Screenshot 2021-04-06 212621](https://user-images.githubusercontent.com/25181332/113741354-2d9d5c80-971f-11eb-9868-eef68f5cb3e4.jpeg)

**Comment by craigchristenson** [comment]
I wasnt able to replicate any issue with the release causing orders to decline. Are you sure that this issue is related to the latest release? Are you still not seeing orders completed in your account?

**Comment by sam24fs** [comment]
We had a few cases reported after the update. However, we didn't receive any complaints recently. I think whatever the cause, the issue has been resolved itself by now.
