### ISSUE TITLE
Need to tick choose: "I have read and agree to the website terms and conditions" before they submit their purchase.

### ISSUE THREAD

**Issue by DAHcod** [2Checkout/woocommerce#4]
Hi @craigchristenson,
I have an issue. At step Pay for order I want users have to tick choose: "I have read and agree to the website terms and conditions" before they submit their purchase.
Now my issue no any tick and users still submit. Can you check this issue need to fix?

See the attached file.

Thank you.
![Screenshot](https://user-images.githubusercontent.com/72394880/97067626-384ea580-1574-11eb-8969-93aecbb073e7.png)

**Comment by DAHcod** [comment]
@craigchristenson Do you have any update for this issue?

**Comment by craigchristenson** [comment]
Sorry for the delay, I missed this issue. Can you confirm which payment method you are using (Convert Plus, Inline, API). I believe your using API based on the previous issue you reported but I just wanted to confirm.

**Comment by DAHcod** [comment]
> Inline

I am using Inline and I have updated the newest version. Please check and fix this issue.
Thank you.

**Comment by craigchristenson** [comment]
We are working on a fix for this and will update you when it has been released.

**Comment by craigchristenson** [comment]
Thank you for reporting this issue. This has been resolved in the latest release 1.2.0. Please make sure that you setup your IPN URL again after installing as it has changed in version 1.2.0.

**Comment by DAHcod** [comment]
> Thank you for reporting this issue. This has been resolved in the latest release 1.2.0. Please make sure that you setup your IPN URL again after installing as it has changed in version 1.2.0.

It is worked perfectly. Thank you.
