### ISSUE TITLE
Inline Checkout and 2PayJS/API

### ISSUE THREAD

**Issue by ddimitrijevic011** [2Checkout/woocommerce#8]
Hello Craig, hello guys, 
I'm have issue with both inline checkout and API payment and I really need your help to fix that. The only module that was working is Convert Plus. So I dont have a clue how to fix that but I checked Console error log so I could explain whats my issue. And I also tried switching to WP default theme but no luck, it was the same. Whats interesting, previous version 1.0.0 was working just fine but not this one. Console Error Log Screenshot attached:  https://pasteboard.co/JATvx13.png

Like I said, I dont have previous experience in JS nor CSS or PHP but I'm learning little by little so any help would be highly appreciated. Thank you in advanced. 
Take you all care!

**Comment by nobel0** [comment]
what is the issue bro?

**Comment by ddimitrijevic011** [comment]
> what is the issue bro?

Hi nobel0 ,
I'm with no previous experience or knowledge about these topics and I'm doing my best to describe the best I can. Two issues that I have.
1. Convert plus receives payment but return URL throwing 404 even though Approved URL was working fine and before issue started, after succesfull payment I was returned to "Order Details" page like it should. 
Screenshots https://pasteboard.co/JC4wp4I.jpg , https://pasteboard.co/JC4x81o.jpg
2. Inline checkout throwing error with twocoinlinecart.js 
https://pasteboard.co/JATvx13.png  
But In previous plugin release everything was working fine but now when I try to reinstall first release 1.0.0 I'm getting the same error like with latest release 1.1.0
Any tips, instructions, tutorial how to fix this is highly appreciated.
Thank you

**Comment by nobel0** [comment]
> > what is the issue bro?
> 
> Hi nobel0 ,
> I'm with no previous experience or knowledge about these topics and I'm doing my best to describe the best I can. Two issues that I have.
> 
> 1. Convert plus receives payment but return URL throwing 404 even though Approved URL was working fine and before issue started, after succesfull payment I was returned to "Order Details" page like it should.
>    Screenshots https://pasteboard.co/JC4wp4I.jpg , https://pasteboard.co/JC4x81o.jpg
> 2. Inline checkout throwing error with twocoinlinecart.js
>    https://pasteboard.co/JATvx13.png
>    But In previous plugin release everything was working fine but now when I try to reinstall first release 1.0.0 I'm getting the same error like with latest release 1.1.0
>    Any tips, instructions, tutorial how to fix this is highly appreciated.
>    Thank you

Sorry i didn't get alert that you have replied..

1. Just to make sure, did you put the right link in your 2co settings?

Anyway, i think the 2co server having problems with the new releases,, as many people are having similar problems...

We all are waiting for them to solve this,, if it solved this is will be a HUGE improvement...
Good luck

**Comment by ddimitrijevic011** [comment]
Thank you Craig, issue resolved but without your help I wasn't able to fix it on my own. But because I'm still learning I needed your help and finaly everything works perfectly fine. All 3 connectors tested and completed succesfuly.
Thank you mate!
Cheers,
Dragan

**Comment by ArbazAhmedKirmani** [comment]
@localpage Hi,
 I'm having a problem with 2co Payment Integration and I'm using ReactJS and NodeJS.
Can you provide me with some tutorials or documentation on how to do that?

I really appreciate any help you can provide.
