### ISSUE TITLE
IPN Callback Url should be " https " not http

### ISSUE THREAD

**Issue by ashik726** [2Checkout/woocommerce#9]
Hello @craigchristenson ,

The plugin IPN Callback url shown http but it's should be " https " . please check the link https://prnt.sc/vlxd2i .
also your documentation IPN Callback url shown http not https https://prnt.sc/vlxdvv . check this your official doc url https://knowledgecenter.2checkout.com/Shopping-cart-integration/Integrate-WooCommerce?mkt_tok=eyJpIjoiTmprMFlqVmhZMkkxTnpNeiIsInQiOiIxTVVZY0pSc0tNc1luZWtQd3ZiclgzNEFVMmgrQUYydGJNQ1cxVVYzeFhYNzhha29sOVNyU09pOTg3SmJlYXdRa0hUaHhlVm5TVGtHZFFBTVwvNHRuVGNWOXJWK2FGMjI5d2RlbWgzdDcxXC9cL1ZpTmVPRlZmVmdkRG54MDZtRHhnQSJ9 

Looking forward your earlier response. 

Thanks 
Ashik

**Comment by nobel0** [comment]
Hi, i agree to Mr. @ashik726 , in the woocommerce plugin settings, the IPN link is shown as http Mr. @craigchristenson ...
I hope you can fix that if this is an issue really..

Thanks

**Comment by ashik726** [comment]
@nobel0 2co response is much more slow....i ask them many days ago but no response....

**Comment by sagitaire123** [comment]
Hi Guys,
http is also working without any problem.
maybe it's better to have https, but http is also working.

**Comment by nobel0** [comment]
> Bro @nobel0 2co response is much more slow....i ask them many days ago but no response....

Yes i know, i hope they can improve in this concern, because this is well known for 2co..

Thanks

**Comment by nobel0** [comment]
> Hi Guys,
> http is also working without any problem.
> maybe it's better to have https, but http is also working.

Ohh okay, this is why Mr. Craig is not responding to this crap, lol ^^ Sorry but we dunno a lot about this stuff. Thanks @craigchristenson  for your efforts.
Thanks for letting us know Mr. @sagitaire123 ..

I hope they can fix the issue ASAP, or at least let us know when or what's the problem ^^

Thanks

**Comment by craigchristenson** [comment]
Thank you for reporting this issue. This has been resolved in the latest release 1.2.0. Please make sure that you setup your IPN URL again after installing as it has changed in version 1.2.0.
